export const footerData = {
    Logo: 'Images/Logo.svg',
    Address: 'Isale Eko Avenue, Dolphin Estate, Ikoyi, Lagos,<br/> Nigeria',
    Address1: '© 2022 Hernalytics',
    Heading2: 'About',
    Story: 'Our Story',
    Blog: 'Blog',
    About: 'About Hernalytics',
    Video: 'Videos',
    Heading3: 'Support',
    Faq: 'FAQs',
    Priv: 'Privacy Policy',
    Term: 'Terms of Service',
    Heading4: 'Let’s chat!',
    Mail: 'hernalytics@gmail.com',
    Phone: '+234 801 234 5678',
    Image1: '/Images/instagramm.svg',
    Image2: '/Images/twitter.svg',
    Image3: '/Images/watsapp.svg',
}